### PR TITLE
Allow discordrpc to silently fail if discord is not open

### PR DESCRIPTION
**Pull request by DipeshAggarwal**
* Create a new function from the init function that only handles connecting to discord.
* Add a new constant, `TRY_RECONNECTING` which determines if we will try to reconnect to discord while setting a activity if we weren't able to connect to discord at launch.
* Remove an unused variable, `is_connected` from RPC class.

### CODE REVIEW

**Review by Senophyx — COMMENTED** [review]
Hey, Thank you for the pull request. I've reviewed your code but haven't had time to try it because I've been quite busy. Have you made sure the code works well? Plus point if you can provide a showcase video.

**Comment by Senophyx** [comment]
Also, why is the function name `crash_if_discord_close`? why not `exit_if_discord_close`? *I'm not forcing though :)*

**Comment by DipeshAggarwal** [comment]
I just wanted to preserve the default behaviour in the parameter name, which was crash when discord was close. I do agree that `exit_if_discord_close` and I can rename the parameter and make the necessary changes if you think that's better. (For the record, I do think your suggestion is better)

**Comment by DipeshAggarwal** [comment]
Pushed the name change.

Also, couldn't do a video but here is a heavily censored screenshot. 
Screenshot 2024-04-10 152058

**Comment by Senophyx** [comment]
> Pushed the name change.
> 
> Also, couldn't do a video but here is a heavily censored screenshot. Screenshot 2024-04-10 152058

What happens if Discord is closed? will it exit immediately? i can't understand it because you are using it directly from python cli :/

**Comment by DipeshAggarwal** [comment]
It doesn't exit. It sets `rpc.ipc.connected` to `False` so when the user tries to call `rpc.set_activity()` we will try to establish a connection once again with discord, provided `TRY_RECONNECTING = True`.

```python
            if not self.exit_if_discord_close:
                raise DiscordNotOpened()
            else:
                log.debug("Discord seems to be close.")
                self.connected = False
```

**Comment by Senophyx** [comment]
Ah okay. Last, can `rpc.ipc.connected` variable accessed the same as `self.is_connected`?

**Comment by DipeshAggarwal** [comment]
I removed `is_connected` from RPC class since it wasn't used.

Now to check if we have made a valid connection to discord, we can call `rpc.ipc.connected` from outside or `self.ipc.connected` from inside the RPC class.

In fact, we use it inside `rpc.set_activity` to see if we are connected to discord.

```python
        if not self.ipc.connected and TRY_RECONNECTING:
            self._setup()

        if not self.ipc.connected:
            return
```

**Comment by Senophyx** [comment]
Okay thank you so much for the contribution. Merge soon.

**Comment by Senophyx** [comment]
Done 👍🏻

**Comment by Senophyx** [comment]
@all-contributors please add @DipeshAggarwal for code

**Pull request merged**
